use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Function call payload
// ---------------------------------------------------------------------------

/// The name and arguments of a function the model wants to call.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FunctionToolCall {
    /// Name of the function to call.
    pub name: String,

    /// JSON-encoded argument object produced by the model.
    pub arguments: String,
}

// ---------------------------------------------------------------------------
// Custom tool call payload
// ---------------------------------------------------------------------------

/// The name and raw input for a custom (non-function) tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomToolCall {
    /// Name of the custom tool to invoke.
    pub name: String,

    /// Raw tool input generated by the model; format depends on the tool's
    /// [`CustomToolFormat`](crate::tool::definition::CustomToolFormat).
    pub input: String,
}

// ---------------------------------------------------------------------------
// Top-level tool call union
// ---------------------------------------------------------------------------

/// A tool invocation requested by the model in an assistant message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ToolCall {
    /// A request to invoke a registered function.
    #[serde(rename = "function")]
    Function {
        /// Unique call identifier used to correlate with the tool-role response.
        id: String,

        function: FunctionToolCall,
    },

    /// A request to invoke a custom tool.
    #[serde(rename = "custom")]
    Custom {
        /// Unique call identifier used to correlate with the tool-role response.
        id: String,

        custom: CustomToolCall,
    },
}

impl Default for ToolCall {
    fn default() -> Self {
        Self::Function {
            id: String::new(),
            function: FunctionToolCall::default(),
        }
    }
}

impl ToolCall {
    /// Returns `true` if this is a function call.
    pub fn is_function(&self) -> bool {
        matches!(self, Self::Function { .. })
    }

    /// Returns `true` if this is a custom tool call.
    pub fn is_custom(&self) -> bool {
        matches!(self, Self::Custom { .. })
    }

    /// The unique call ID, regardless of variant.
    pub fn id(&self) -> &str {
        match self {
            Self::Function { id, .. } | Self::Custom { id, .. } => id,
        }
    }

    /// The tool/function name being invoked, regardless of variant.
    pub fn name(&self) -> &str {
        match self {
            Self::Function { function, .. } => &function.name,
            Self::Custom { custom, .. } => &custom.name,
        }
    }
}

// ---------------------------------------------------------------------------
// Backward-compat type aliases
// ---------------------------------------------------------------------------

pub type ChatCompletionMessageToolCall = ToolCall;
